### PR TITLE
Notebooks for Air Quality Plots

### PR DESCRIPTION
**Pull request by MilesClement**
Notebooks for Covid Air Quality plots - @lukessmith can you have a check to make sure they work (particularly the pickle stuff as thats new to me - file path for read/write will need updating for the relevant filesystem). Let me know if you have any suggestions.

### CODE REVIEW

**Comment by MilesClement** [comment]
Just added a notebook for producing aggregated plots across all stations, as well as a small update in the baseline data notebook.

**Comment by lukeshope** [comment]
Hi Miles,

Sorry it's taken so long. I'm not trying to be overwhelmingly negative here, this is just the fun of the code review process. It's a lot like peer review, but you don't get any credit at the end.

# General

Make filenames consistent for the scripts. Hyphens instead of underscores etc. All lowercase (the Unix way :-)).

Paths need to be relative, not absolute, and definitely not on the `C:\` drive.

# Baseline and update script

Can you use an additional API request to make the script future-proofed if any other precision AQ stations are added? In other words, avoid hard-coding the AQ_MONITOR names.

Add an hour or so on to the current time when making the API request, in case the server clocks aren't fully synced.

Path is hard-coded as `C:\...`, and needs changing to `../cache/`.

Use `https://newcastle.urbanobservatory.ac.uk/api/...` as the API request prefix.

Make pickle filenames all lowercase, or better yet, a single timeseries with all of the precision stations in? Look at the `.join` method on dataframes.

# Plots

If you combine all the sensors into a single dataframe, you can use the columns in the frame instead of hard-coding the sensor list.

Let's try get the fill_between working for the percentile ranges :-)

Can you try make the style and colours consistent with the other notebooks? Figure sizes should be (18, 6.5)ish etc.

**Comment by MilesClement** [comment]
Cheers Luke -  some of the things you've highlighted I figured would need updating (filepaths etc), wasn't 100% sure what to switch them too at the time, but will tweak to ../cache/.

I'll update everything today/tomorrow as you've suggested.

Been working on getting the plots more consistent with how you've done them - got fill_between working in another plot, so should be able to transfer across.

**Comment by MilesClement** [comment]
Hi Luke,
 
Had a crack at doing the changes you highlighted. 

Only thing I couldn't quite get working was the legend (figlegend) for the baseline data - for now I have added these variables to the main legend.

Let me know if there are any changes you'd want/suggest me to do.

Will look at making the other notebooks consistent with the other plots next week.

**Comment by MilesClement** [comment]
Just pushed the latest notebooks, which includes new baseline and plotting ones. Fairly certain it'll work live, but there are a few things for me to continue looking at (see below). It should produce additional plots for each month (so come April will show April then March for each variable/sensor).

Some outstanding things for me to look into:
- When more plots are added (when it rolls over to a new month), suptitle positioning changes. Still relatively new to matplotlib, so unsure if there's a better way of setting up subplots/titles etc. Will keep tweaking this, but should be good until 6th April (first Monday).
- Still can't get legend below plots to work (currently added baseline info into main plot legend). Have gotten the shaded area in, but not managed the median line. Have removed the code for this currently, will have another attempt tomorrow (and may ask for your assisstance).
- Thinking of limiting plots to 2 months worth so not to produce lots of charts if the virus goes on longer - thoughts?

Sorry if the code is messy - was trying to get something working asap, and still shaking of the rustiness/learning about plotting with python. Can work on neatening up if you wish.

**Review by lukeshope — APPROVED** [review]
Made a few changes to this locally to make the styling more consistent.

Otherwise all looks good. Already merged direct with my changes.

**Pull request closed without merging**
